### ISSUE TITLE
Build fails with error

### ISSUE THREAD

**Issue by littleblackfish** [heerme/seql-sequence-learner#3]
If I compile with gcc 8.4, I get: 
```
seql_mkmodel.cpp:117:78: error: no matching function for call to ‘make_pair<const char*, double>(const char*, double&)’
     ary2.push_back (std::make_pair <const char*, double>(it->first.c_str(), a));
```
If I compile with gcc 10, I get:

```
seql_mkmodel.cpp:117:77: error: cannot bind rvalue reference of type ‘double&&’ to lvalue of type ‘double’
  117 |     ary2.push_back (std::make_pair <const char*, double>(it->first.c_str(), a));
```

Unfortunately, I don't have any earlier versions of gcc readily available for my distribution.

**Comment by heerme** [comment]
I have just downloaded the code now, on a machine with Mac OS Catalina. I installed the command line developer tools and then ran "make" in the main folder with the code. Runs perfectly well for me this way, are you still facing any issues?

**Comment by littleblackfish** [comment]
I am on a linux machine and problem persists for me. Unfortunately I gave up as this was one of the many tools I was experimenting with.

**Comment by heerme** [comment]
Thanks for letting me know, I will see if I can reproduce the error on a Linux machine with latest gcc.

**Comment by svgsponer** [comment]
I just made a pull request that should fix this compiler issues, however, could not check on apple devices and if it still compiles with older compiler (<GCC 7.5)

**Comment by svgsponer** [comment]
@littleblackfish in case you would like to try the fix before the pull request is accepted you can apply it to your local code by executing the following line:

`curl -L https://github.com/heerme/seql-sequence-learner/pull/4.patch | git apply`

In case you have further problems, please do not hesitate to ask here again.

**Comment by heerme** [comment]
I have merged the pull request. This code now compiles on Linux with latest gcc version and on Mac OS Catalina with command line developer tools installed (to be able to run "make"). Many thanks Severin for the fix!
